#!/usr/bin/env bash
# The `ddeploy` command: a small wrapper at /usr/local/bin/ddeploy that
# runs this checkout's provision.sh from anywhere, plus bash completion.
# Installed by `init`, or on its own by `install-cli` (an already-set-up
# server, or after moving the checkout).
#
# A generated wrapper, not a symlink: provision.sh finds lib/ relative
# to its own path, which a symlink in /usr/local/bin would break. The
# checkout's path is baked in at install time — re-run install-cli if
# the checkout moves.
#
# When not run as root, the wrapper re-runs itself as
# `sudo <checkout>/provision.sh ...` — sudo on provision.sh itself, not on
# the wrapper, so a sudoers rule scoped to provision.sh (e.g. for a CI
# deploy key) keeps matching either way. Help needs no root and never
# prompts.

CLI_BIN="/usr/local/bin/ddeploy"
CLI_COMPLETION="/etc/bash_completion.d/ddeploy"

usage_install_cli() {
    cat <<'EOF'
usage: ./provision.sh install-cli

Installs /usr/local/bin/ddeploy (runs this checkout from anywhere, adds
sudo itself when needed) and bash completion for it. `init` does this
too; run it on its own after moving the checkout.
EOF
}

install_cli() {
    local tmp; tmp="$(mktemp)"
    cat > "$tmp" <<EOF
#!/usr/bin/env bash
# ddeploy — generated by 'provision.sh install-cli' (also run by init).
# Runs the ddeploy checkout below; re-run install-cli rather than
# editing this if the checkout moves.
DDEPLOY_DIR=$(printf '%q' "$PROVISIONER_DIR")

for arg in "\$@"; do
    case "\$arg" in -h|--help) exec "\$DDEPLOY_DIR/provision.sh" "\$@" ;; esac
done
case "\${1:-}" in
    ""|help) exec "\$DDEPLOY_DIR/provision.sh" "\$@" ;;
esac
if [[ "\$EUID" -ne 0 ]]; then
    exec sudo "\$DDEPLOY_DIR/provision.sh" "\$@"
fi
exec "\$DDEPLOY_DIR/provision.sh" "\$@"
EOF
    install -m 755 -o root -g root "$tmp" "$CLI_BIN"
    rm -f "$tmp"

    # Command names come from the live usage text (so a new command
    # completes without touching this); site names from SITES_ROOT,
    # which is world-listable (nginx has to traverse it).
    mkdir -p "$(dirname "$CLI_COMPLETION")"
    cat > "$tmp" <<EOF
# bash completion for ddeploy — generated by 'provision.sh install-cli'.
_ddeploy() {
    local cur="\${COMP_WORDS[COMP_CWORD]}"
    if [[ "\$COMP_CWORD" -eq 1 ]]; then
        local cmds
        cmds="\$($(printf '%q' "$PROVISIONER_DIR")/provision.sh help 2>/dev/null | awk '/^  [a-z]/{print \$1}')"
        mapfile -t COMPREPLY < <(compgen -W "\$cmds" -- "\$cur")
    elif [[ "\$COMP_CWORD" -eq 2 && "\${COMP_WORDS[1]}" != install-cli ]]; then
        local sites
        sites="\$(ls -1 $(printf '%q' "$SITES_ROOT") 2>/dev/null)"
        [[ "\${COMP_WORDS[1]}" == logs ]] && sites+=" webhook webhook-other backup-uploads backup-database prune-previews"
        mapfile -t COMPREPLY < <(compgen -W "\$sites" -- "\$cur")
    fi
}
complete -F _ddeploy ddeploy
EOF
    install -m 644 -o root -g root "$tmp" "$CLI_COMPLETION"
    rm -f "$tmp"
    log_info "installed $CLI_BIN (runs $PROVISIONER_DIR/provision.sh) and bash completion — open a new shell for completion"
}

cmd_install_cli() {
    [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]] && { usage_install_cli; return 0; }
    load_conf
    require_root
    install_cli
}
