#!/usr/bin/env bash
# `init-web` — the server side of the web UI (webddeploy): its system
# user, the one sudoers rule it gets, and its nginx vhost. The app itself
# (a Node service) is installed from the webddeploy repo; this is only
# the part that decides what it may do as root, which belongs with the
# rest of ddeploy's security model (docs/security.md, "The web UI").
#
# The rule is `provision.sh api *` and nothing else: lib/cmd_api.sh is
# the web UI's whole reach. sudo's env_reset (the Ubuntu default) means
# the web user can't pass DDEPLOY_* variables through either.

WEB_SUDOERS="/etc/sudoers.d/ddeploy-web"
WEB_VHOST="/etc/nginx/sites-available/ddeploy-web.conf"

usage_init_web() {
    cat <<'EOF2'
usage: ddeploy init-web [--disable]

Sets up what the web UI (webddeploy) needs from this server:
  - system user WEB_USER (default ddeploy-web), state dir /var/lib/webddeploy
  - /etc/sudoers.d/ddeploy-web: WEB_USER may run `provision.sh api *` as
    root, nothing else
  - nginx vhost for WEB_HOSTNAME (default ddeploy.<BASE_DOMAIN>, on the
    wildcard certificate) proxying to WEB_LISTEN (default 127.0.0.1:8790)

`init` runs this too when WEB_ENABLED=true. --disable removes the sudoers
rule and the vhost (the user and its state are kept).
EOF2
}

cmd_init_web() {
    local disable=0
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -h|--help) usage_init_web; return 0 ;;
            --disable) disable=1 ;;
            *) die "unknown option: $1" ;;
        esac
        shift
    done
    load_conf
    require_root
    if [[ "$disable" -eq 1 ]]; then
        disable_web
    else
        install_web
    fi
    nginx -t && systemctl reload nginx
}

install_web() {
    local user="$WEB_USER" hostname="$WEB_HOSTNAME" port="${WEB_LISTEN##*:}"
    [[ "$user" =~ ^[a-z_][a-z0-9_-]{0,31}$ ]] || die "WEB_USER ('$user') is not a valid user name"
    validate_hostname "$hostname" "WEB_HOSTNAME"
    [[ "$port" =~ ^[0-9]{2,5}$ ]] || die "WEB_LISTEN ('$WEB_LISTEN') must be host:port"
    # The wildcard certificate covers exactly one label under BASE_DOMAIN.
    local label="${hostname%".$BASE_DOMAIN"}"
    if [[ "$label" == "$hostname" || "$label" == *.* ]]; then
        die "WEB_HOSTNAME ('$hostname') must be one label under $BASE_DOMAIN (e.g. ddeploy.$BASE_DOMAIN) to be covered by the wildcard certificate"
    fi

    if ! id -u "$user" >/dev/null 2>&1; then
        useradd --system --home-dir /var/lib/webddeploy --no-create-home --shell /usr/sbin/nologin "$user"
        log_info "created system user $user"
    fi
    install -d -m 700 -o "$user" -g "$user" /var/lib/webddeploy
    install -d -m 750 -o root -g "$user" /etc/webddeploy

    local tmp; tmp="$(mktemp)"
    cat > "$tmp" <<EOF2
# Generated by 'ddeploy init-web' — the web UI's only root access.
# See lib/cmd_api.sh for everything this reaches. Re-run init-web rather
# than editing this by hand.
Defaults:$user !requiretty
$user ALL=(root) NOPASSWD: $PROVISIONER_DIR/provision.sh api *
EOF2
    visudo -cqf "$tmp" || { rm -f "$tmp"; die "generated sudoers rule failed visudo -c — nothing installed"; }
    install -m 440 -o root -g root "$tmp" "$WEB_SUDOERS"
    rm -f "$tmp"
    log_info "installed $WEB_SUDOERS ($user -> provision.sh api)"

    render_template "$PROVISIONER_DIR/templates/web-vhost.conf.tmpl" "$WEB_VHOST" \
        "HOSTNAME=$hostname" "CERT_NAME=$BASE_DOMAIN" "PORT=$port" "IMPORT_MAX=$(( $(api_import_max_bytes) / 1024 / 1024 ))m" "UPLOAD_MAX=$(( $(api_upload_max_bytes) / 1024 / 1024 ))m"
    ln -sf "$WEB_VHOST" /etc/nginx/sites-enabled/ddeploy-web.conf
    log_info "installed web UI vhost: https://$hostname -> 127.0.0.1:$port"
    log_info "next: install the webddeploy app (see its README) listening on 127.0.0.1:$port as $user"
}

disable_web() {
    rm -f "$WEB_SUDOERS" /etc/nginx/sites-enabled/ddeploy-web.conf "$WEB_VHOST"
    log_info "web UI sudoers rule and vhost removed"
}
